name: Update arXiv Papers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-papers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv
      
      - name: Run fetcher
        run: |
          mkdir -p data
          python fetch_papers.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git stash -u
          git pull origin main
          git stash pop
          git add data/papers.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update papers data" && git push)
